### ISSUE TITLE
공용 컴포넌트 스타일링

### ISSUE THREAD

**Issue by page1597** [TEAM-MUNA/muna#6]
## 💼 작업 설명

전체 프로젝트에서 쓰일 공용 컴포넌트를 만든다.

## ✅ To-do

- [x] Icon
- [x] Button
- [x] Tag
- [x] StarTag
- [x] Dropdown
- [x] Tab
- [x] MultiSelectTab
- [x] Input
- [x] Header
- [x] Title
- [x] ReviewTitle
- [x] ConcertCard
- [x] Bar
- [x] ReviewBar
- [x] Avatar
- [x] StarForm
- [x] StarScoreButton
- [x] StarScore

**Comment by diayeri** [comment]
제가 새로 맡은 부분은 여기에 리스트 추가해놓겠습니다 :)

- [ ] settings
  - [ ] Toggle
  - [ ] ColumnMenu
  - [ ] InputUserImage
- [ ] CardReview
- [ ] CardPoster
